server:
  port: ${PORT:8861}
message: Configuracion de Customer en el servidor levantado!
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##bdprueba
    password: C##bdprueba
  jpa:
    hibernate:
      ddl-auto: update
      database-platfomr: org.hibernate.dialect.OracleDialect
