server:
   port: ${PORT:8815}
message: Configuracion de producto servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8860
